"""Generate the offline pixel-map coast from DataSF's public-domain shoreline."""
import json
from pathlib import Path
from urllib.request import urlopen

URL = 'https://data.sf.gov/resource/txuc-3kzm.geojson?$limit=1000'
OUTPUT = Path(__file__).resolve().parents[1] / 'web/sf-coast-data.js'


def simplify(points, tolerance=0.00006):
    if len(points) < 3:
        return points
    a, b = points[0], points[-1]
    dx, dy = b[0]-a[0], b[1]-a[1]
    length = dx*dx+dy*dy
    def distance(p):
        t = max(0, min(1, ((p[0]-a[0])*dx+(p[1]-a[1])*dy)/length)) if length else 0
        return ((p[0]-a[0]-t*dx)**2+(p[1]-a[1]-t*dy)**2)**0.5
    index = max(range(1, len(points)-1), key=lambda i: distance(points[i]))
    if distance(points[index]) <= tolerance:
        return [a, b]
    return simplify(points[:index+1], tolerance)[:-1]+simplify(points[index:], tolerance)


if __name__ == '__main__':
    print('Downloading public-domain DataSF shoreline...', flush=True)
    with urlopen(URL, timeout=45) as response:
        data = json.load(response)
    polygons = []
    for feature in data['features']:
        geometry = feature.get('geometry')
        if not geometry:
            continue
        for polygon in geometry['coordinates']:
            if any(-122.53 < p[0] < -122.35 and 37.70 < p[1] < 37.85 for p in polygon[0]):
                polygons.append([[[round(p[0], 6), round(p[1], 6)] for p in simplify(ring)] for ring in polygon])
    assert polygons, 'The source returned no SF shoreline geometry'
    result = {'source':URL,'license':'Public Domain Dedication and License','simplification_degrees':0.00006,'polygons':polygons}
    OUTPUT.write_text('// Generated by scripts/build_sf_coast.py; geographic data, not invented coastline.\nexport const SF_COAST = '+json.dumps(result,separators=(',', ':'))+';\n')
    print(f'Wrote {len(polygons)} land polygons to {OUTPUT.name}', flush=True)
